version: '3.1'
name: api-tuinbouw-production

services:
  mongodb:
    image: mongo
    restart: on-failure:5 # On error, try to restart for a maximum of 5 times
    ports:
      - 27027:27017
    environment:
      MONGO_INITDB_DATABASE: api
    volumes:
      - dbvolumetuinbouwproduction:/data/db 
      

  api:
    image: jinlei2000/api-tuinbouw-production-api # change to your docker hub username
    build:
      context: ../.
      dockerfile: packages/api/Dockerfile
    env_file:
      - ./../packages/api/.env.production.local
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/my-google-secret
    ports:
      - 3001:3001 # External:What Is Set In Main.ts
    secrets:
      - my-google-secret  



  tuinbouw:
    image: jinlei2000/api-tuinbouw-production-tuinbouw # change to your docker hub username
    build:
      context: ../.
      dockerfile: packages/tuinbouw/Dockerfile
    ports:
      - 8081:80



volumes:
  dbvolumetuinbouwproduction:

secrets:
  my-google-secret:
    file: ../credentials.json # change location