# deployment-mongo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: tuinbouw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: api
          volumeMounts:
            - name: dbvolumetuinbouwproduction
              mountPath: /data/db

      volumes:
        - name: dbvolumetuinbouwproduction
          persistentVolumeClaim:
            claimName: mongodb-pvc
